# Generated by Django 5.2.1 on 2025-06-02 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='director',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'director'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_schools', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cycle', models.CharField(choices=[('PRESCHOOL', 'Préscolaire'), ('PRIMARY', 'Primaire')], default='PRIMARY', max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='levels', to='schools.school')),
            ],
            options={
                'ordering': ['school', 'name'],
                'unique_together': {('name', 'school')},
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('academic_year', models.CharField(help_text='Ex: 2023-2024', max_length=9)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='schools.level')),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
                'ordering': ['level__school__name', 'level__name', 'name'],
                'unique_together': {('name', 'level', 'academic_year')},
            },
        ),
    ]
